dataset_name: 'tcga_renal'
paths:
  data_dir:
    kich: "/home/mvu9/processing_datasets/processing_tcga_256/kich/features_fp"
    kirc: "/home/mvu9/processing_datasets/processing_tcga_256/kirc/features_fp"
    kirp: "/home/mvu9/processing_datasets/processing_tcga_256/kirp/features_fp"
  save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/clam_tcga_renal_result"
  result_dir: "/home/mvu9/processing_datasets/processing_tcga_256/clam_tcga_renal_results" # where we save all the check point
  split_folder: "/home/mvu9/processing_datasets/processing_tcga_256/splits_csv_tcga_renal"
  # for_ig_checkpoint_path_fold_1: "/home/mvu9/processing_datasets/processing_tcga_256/result_2025-05-19_15-16-56/s_1_checkpoint.pt"
  for_ig_checkpoint_path_fold_1: "/home/mvu9/processing_datasets/processing_tcga_256/result_2025-05-20_03-31-00_ep200/s_1_checkpoint.pt"
  attribution_scores_folder: "/home/mvu9/cig_attributions/attr_scores/tgca_renal"
  ig_clam_plot_folder: "/home/mvu9/cig_attributions/attr_scores_clam_plot/tcga_renal"   
  memmap_path: "/home/mvu9/cig_attributions/memmap_tmp_tcga_renal"
  slide_dir: '/home/mvu9/datasets/TCGA-datasets'
  baseline_dir_fold_1: "/home/mvu9/processing_datasets/processing_tcga_256/baseline_tcga_renal/baseline_clam/fold_1"  



  
patterns: 
  h5_files: "/home/mvu9/processing_datasets/processing_tcga_256/*/features_fp/h5_files" 

label_dict: {'KIRP': 0, 'KIRC': 1, 'KICH': 2}
embed_dim: 1024
lr: 0.0001
label_frac: 1.0
reg: 0.00001
seed: 42
log_data: false
testing: false
early_stopping: false
opt: adam
drop_out: 0.25
bag_loss: ce
model_type: clam_sb
exp_code: clam_tcga
weighted_sample: false
model_size: small
no_inst_cluster: false
inst_loss: null
subtyping: false
bag_weight: 0.7
B: 8
n_classes: 3