dataset_name: 'camelyon16'
paths:
  pt_files: "/home/mvu9/processing_datasets/processing_camelyon16/features_fp"
  data_dir: "/home/mvu9/processing_datasets/processing_camelyon16/features_fp" # some code use pt_files as data_dir
  # save_dir: "/home/mvu9/processing_datasets/processing_camelyon16/clam_result"
  # result_dir: "/home/mvu9/processing_datasets/processing_camelyon16/results" # where we save all the check point
  result_dir: "/home/mvu9/processing_datasets/processing_camelyon16/clam_results" #fold1/result_final_ep200 
  split_folder: "/home/mvu9/processing_datasets/processing_camelyon16/splits_csv" 
  # for_ig_checkpoint_path_fold_1: "/home/mvu9/processing_datasets/processing_camelyon16/result_2025-05-18/result_2025-05-18_22-23-56/s_1_checkpoint.pt"
  for_ig_checkpoint_path_fold_1: "/home/mvu9/processing_datasets/processing_camelyon16/clam_result/result_final_ep200/s_1_checkpoint.pt"
  # attribution_scores_folder: "/home/mvu9/cig_attributions/attr_scores/camelyon16"
  attribution_scores_folder: "/home/mvu9/cig_attributions/attr_scores_no_class/camelyon16" 
  ig_clam_plot_folder: "/home/mvu9/cig_attributions/attr_scores_clam_plot/camelyon16"  
  memmap_path: "/home/mvu9/cig_attributions/memmap_tmp_camelyon16"
  slide_dir: "/home/mvu9/datasets/camelyon16/raw_data/camelyon16/images"
  h5_files: "/home/mvu9/processing_datasets/processing_camelyon16/features_fp/h5_files" 
  feature_files: "/home/mvu9/processing_datasets/processing_camelyon16/features_fp/pt_files"  
  metrics_dir: "/home/mvu9/processing_datasets/processing_camelyon16/metrics"
  dataset_mean: "/home/mvu9/processing_datasets/processing_camelyon16/dataset_mean_variance" 

  baseline_dir_fold_1: "/home/mvu9/processing_datasets/processing_camelyon16/baseline/baseline_clam/fold_1"  
  predictions_dir: "/home/mvu9/processing_datasets/processing_camelyon16/clam_predictions"
  metrics_dir: "/home/mvu9/processing_datasets/processing_camelyon16/clam_metrics"

fold_number: 5 
label_dict:
  0: "normal"
  1: "tumor" 

embed_dim: 1024
lr: 0.0001
label_frac: 1.0
reg: 0.00001
seed: 42
log_data: false
testing: false
early_stopping: false
opt: adam
drop_out: 0.25
bag_loss: ce
model_type: clam_sb
exp_code: clam_camelyon16
weighted_sample: false
model_size: small
no_inst_cluster: false
inst_loss: null
subtyping: false
bag_weight: 0.7
B: 8
n_classes: 2
