dataset_name: 'camelyon16'
paths:
  pt_files: "/home/mvu9/processing_datasets/processing_camelyon16/features_fp"
  save_dir: "/home/mvu9/processing_datasets/processing_camelyon16"
  result_dir: "/home/mvu9/processing_datasets/processing_camelyon16/results" # where we save all the check point
  split_folder: "/home/mvu9/processing_datasets/processing_camelyon16/splits_csv" 

embed_dim: 1024
# max_epochs: 2
lr: 0.0001
label_frac: 1.0
reg: 0.00001
seed: 42
log_data: false
testing: false
early_stopping: false
opt: adam
drop_out: 0.25
bag_loss: ce
model_type: clam_sb
exp_code: clam_camelyon16
weighted_sample: false
model_size: small
no_inst_cluster: false
inst_loss: null
subtyping: false
bag_weight: 0.7
B: 8
k_start: 1 
k_end: 5 
label_dict 