paths:
  source_dir: "/home/mvu9/datasets/TCGA-datasets/LUAD"
  save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/LUAD"
  patch_h5_dir: "/home/mvu9/processing_datasets/processing_tcga_256/LUAD/patches_h5"
  patch_png_dir: "/home/mvu9/processing_datasets/processing_tcga_256/LUAD/patches_png"
  mask_save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/LUAD/masks"
  only_mask_save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/LUAD/only_masks"
  stitch_save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/LUAD/graph_1024"
  slide_name_file: "/home/mvu9/datasets/TCGA-metadata/LUAD/slides.xlsx"
  uuid_name_file: "/home/mvu9/datasets/TCGA-metadata/LUAD/uuids.xlsx"
  preset_file: "/home/mvu9/folder_04_ma/wsi-data/presets/tcga_vilamil.csv"
  slide_list:  "/home/mvu9/processing_datasets/processing_tcga_256/LUAD/process_list_autogen.csv" 
  
# Processing parameters
processing:
  patch_size: 256
  step_size: 256
  patch_level: 0
  seg: true
  patch: true
  stitch: false
  auto_skip: true

feature_extraction:
  model_name: "resnet50_trunc"
  batch_size: 256
  target_patch_size: 224
  slide_ext: ".svs"  # Adjust if TCGA-LUAD uses .tif or other format
  no_auto_skip: false  # Inverted from processing.auto_skip