# DSMIL Training Configuration
# Train DSMIL on 20x patch features learned by SimCLR

# Model Configuration
num_classes: 2  # Number of output classes
feats_size: 1024  # Dimension of the feature size
model: "dsmil"  # MIL model

# Training Parameters
lr: 0.0001  # Initial learning rate
num_epochs: 50  # Number of total training epochs
stop_epochs: 10  # Skip remaining epochs if training has not improved after N epochs
weight_decay: 0.001  # Weight decay

# Hardware Configuration
gpu_index: [0]  # GPU ID(s)

# Dataset Configuration
dataset: "TCGA-lung-default"  # Dataset folder name
split: 0.2  # Training/Validation split

# Model Architecture
dropout_patch: 0.0  # Patch dropout rate
dropout_node: 0.0  # Bag classifier dropout rate
non_linearity: 1.0  # Additional nonlinear operation
average: false  # Average the score of max-pooling and bag aggregating

# Evaluation Configuration
eval_scheme: "5-fold-cv"  # Options: 5-fold-cv | 5-fold-cv-standalone-test | 5-time-train+valid+test
k_start: 1  # Start fold number
k_end: 1  # End fold number

# Config Path
config: "./configs_simea/dsmil_camelyon16.yaml"

split_folder: "/home/mvu9/processing_datasets/processing_camelyon16/splits_csv"
data_dir: "/home/mvu9/processing_datasets/processing_camelyon16/features_fp"
save_path: "/home/mvu9/processing_datasets/processing_camelyon16/dsmil_results"