# Training Configuration File

# Basic Settings
name: "dtfd_tcga_renal"
EPOCH: 200
epoch_step: "[100]"
device: "cuda"
isPar: false

# Logging
log_dir: "/home/mvu9/processing_datasets/processing_tcga_256/dtfd_tcga_lung_results_1fold"
train_show_freq: 40

# Model Parameters
droprate: 0.0
droprate_2: 0.0
lr: 0.0001
weight_decay: 0.0001
lr_decay_ratio: 0.2

# Training Parameters
batch_size: 1
batch_size_v: 1
num_workers: 4
num_cls: 2

# Group Settings
numGroup: 4
total_instance: 4
numGroup_test: 4
total_instance_test: 4

# Model Architecture
mDim: 512
numLayer_Res: 0

# Training Control
grad_clipping: 5.0
isSaveModel: true
temperature: 1.0
num_MeanInference: 1

# Distillation Settings
distill_type: "AFS"  # Options: MaxMinS, MaxS, AFS

# Paths
split_folder: "/home/mvu9/processing_datasets/processing_tcga_256/splits_csv_tcga_lung"
save_path: "/home/mvu9/processing_datasets/processing_tcga_256/dtfd_tcga_lung_results_1fold"
config_path: "./configs_simea/dtfd_tcga_lung.yaml"

# Data Directory Mapping
data_dir_map:
  LUAD: "/home/mvu9/processing_datasets/processing_tcga_256/luad/features_fp"
  LUSC: "/home/mvu9/processing_datasets/processing_tcga_256/lusc/features_fp"
paths:
  predictions_dir: "/home/mvu9/processing_datasets/processing_tcga_256/dtfd_tcga_lung_predictions"
  split_folder: "/home/mvu9/processing_datasets/processing_tcga_256/splits_csv_tcga_lung"
  data_dir:
    luad: "/home/mvu9/processing_datasets/processing_tcga_256/luad/features_fp"
    lusc: "/home/mvu9/processing_datasets/processing_tcga_256/lusc/features_fp"
dataset_name: 'tcga_lung'
label_dict: {'LUAD': 0, 'LUSC': 1}