dataset_name: 'tcga_lung'
paths:
  data_dir:
    lusc: "/home/mvu9/processing_datasets/processing_tcga_256/lusc/features_fp"
    luad: "/home/mvu9/processing_datasets/processing_tcga_256/luad/features_fp"
  save_dir: "/home/mvu9/processing_datasets/processing_tcga_256/mlp_tcga_lung_result"
  result_dir: "/home/mvu9/processing_datasets/processing_tcga_256/mlp_tcga_lung_results" # where we save all the check point
  split_folder: "/home/mvu9/processing_datasets/processing_tcga_256/splits_csv_tcga_lung"
  # for_ig_checkpoint_path_fold_1: "/home/mvu9/processing_datasets/processing_tcga_256/result_2025-05-19_15-16-56/s_1_checkpoint.pt"
  # for_ig_checkpoint_path_fold_1: "/home/mvu9/processing_datasets/processing_tcga_256/mlp_tcga_lung_result/result_final_ep200/s_1_checkpoint.pt"
  # for_ig_checkpoint_path_fold_1: "/home/mvu9/processing_datasets/processing_tcga_256/result_2025-05-20_03-31-00_ep200/s_1_checkpoint.pt"
  attribution_scores_folder: "/home/mvu9/cig_attributions/attr_scores_no_class/tcga_lung/mlp"
  attribution_scores_plot: "/home/mvu9/cig_attributions/attr_scores_plot/tcga_lung/mlp"  
  metadata_plot_dir: "/home/mvu9/cig_attributions/metadata_plot/tcga_lung/mlp"    

  # attribution_scores_folder: "/home/mvu9/cig_attributions/attr_scores/tcga_lung"
  ig_mlp_plot_folder: "/home/mvu9/cig_attributions/attr_scores_mlp_plot/tcga_lung"   
  memmap_path: "/home/mvu9/cig_attributions/memmap_tmp_tcga_lung"
  slide_dir: '/home/mvu9/datasets/TCGA-datasets'
  predictions_dir: "/home/mvu9/processing_datasets/processing_tcga_256/mlp_tcga_lung_predictions" 
  baseline_dir_fold_1: "/home/mvu9/processing_datasets/processing_tcga_256/baseline_tcga_lung/baseline_mlp/fold_1"  
  metrics_dir: "/home/mvu9/processing_datasets/processing_tcga_256/mlp_tcga_lung_metrics" 
  
patterns: 
  h5_files: "/home/mvu9/processing_datasets/processing_tcga_256/*/features_fp/h5_files" 

label_dict: {'LUAD': 0, 'LUSC': 1}
n_classes: 2
seed: 1
lr: 0.0001
reg: 0.00001
drop_out: 0.25
model_size: small
gate: true
subtyping: false
embed_dim: 1024 
n_classes: 2
early_stopping: true
patience: 20 