#   source_dir: "/project/hnguyen2/mvu9/datasets/camelyon16/raw_data/camelyon16/images"
#   save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16"
#   patch_h5_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/patches_h5"
#   patch_png_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/patches_png"
#   mask_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/masks"
#   only_mask_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/only_masks"
#   stitch_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/graph_1024"
#   slide_name_file: "/project/hnguyen2/mvu9/datasets/TGCA-metadata/CAMELYON16/slides.xlsx"

# # Processing parameters
# processing:
#   patch_size: 1024
#   step_size: 1024
#   patch_level: 1
#   seg: true
#   patch: true
#   stitch: false
  # auto_skip: true



paths:
  source: "/project/hnguyen2/hqvo3/Datasets/digital_pathology/public/CAMELYON16/images" 
  save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16"
  # patch_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/patches"
  patch_png_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/patches_png"
  patch_h5_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/patches"
  mask_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/masks"
  stitch_save_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/stitches"
  slide_list:  "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/process_list_autogen.csv" 
  feature_fp: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/features_fp"
  pt_files: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/features_fp/pt_files"
  ht_files: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/features_fp/h5_files"
  split_folder: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/splits_csv"

fold_number: 5 
label_dict:
  0: "normal"
  1: "tumor"
processing:
  patch_size: 256
  step_size: 256
  patch_level: 0
  seg: true
  patch: true
  stitch: false 
  auto_skip: false 

segmentation:
  seg_level: -1
  sthresh: 8
  mthresh: 7
  close: 4
  use_otsu: false
  keep_ids: "none"
  exclude_ids: "none"

filtering:
  a_t: 100
  a_h: 16
  max_n_holes: 8

visualization:
  vis_level: -1
  line_thickness: 250

patching:
  use_padding: true
  contour_fn: "four_pt"
  # white_thresh: 5
  # black_thresh: 50

feature_extraction:
  model_name: resnet50_trunc
  batch_size: 256
  target_patch_size: 224
  slide_ext: .tif
  no_auto_skip: False