# Configuration file for training arguments
name: "dtfd_camelyon16"
EPOCH: 200
epoch_step: "[100]"
device: "cuda"
isPar: false
log_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/dtfd_camelyon16/results"
train_show_freq: 40
droprate: 0.0
droprate_2: 0.0
lr: 0.0001
weight_decay: 0.0001
lr_decay_ratio: 0.2
batch_size: 1
batch_size_v: 1
num_workers: 4
num_cls: 2
numGroup: 4
total_instance: 4
numGroup_test: 4
total_instance_test: 4
mDim: 512
grad_clipping: 5.0
isSaveModel: true
debug_DATA_dir: ""
numLayer_Res: 0
temperature: 1.0
num_MeanInference: 1
distill_type: "AFS"  # Options: MaxMinS, MaxS, AFS
k_start: 1
k_end: 5
split_folder: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/splits_csv"
data_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/features_fp"
log_dir: "/project/hnguyen2/mvu9/processing_datasets/processing_camelyon16/dtfd_results"